LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE        := TalpaGameCenter
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES     := TalpaGameCenter_201611141500.apk
LOCAL_MODULE_PATH   := $(TARGET_OUT_APPS_PRIVILEGED)
LOCAL_CERTIFICATE   := platform
include $(BUILD_PREBUILT)
